### ISSUE TITLE
glycoRDFの単糖ネームを取得する場合、rdfs:label?

### ISSUE THREAD

**Issue by aokinobu** [glycoinfo/GlycoRDF#2]
単糖情報を取得してComponentを作成するとき、単糖のネームを設定したい。

```
PREFIX wurcs: <http://www.glycoinfo.org/glyco/owl/wurcs#>
SELECT distinct ?mono
                FROM <http://rdf.glytoucan.org/wurcs/ms>
                WHERE{
?mono a wurcs:Monosaccharide .
}
limit 100
```
はサンプルデータ

    http://rdf.glycoinfo.org/glycan/wurcs/2.0/Monosaccharide/a2112A-1a_1-5_2%2AN

の結果、"a2112A-1a_1-5_2%2AN"だけを取得したいです。

RDFだとどう定義する？SIOある？

    <http://rdf.glycoinfo.org/glycan/wurcs/2.0/Monosaccharide/Aad211d2h-2a_2-6_5%2ANCC%2F3%3DO>  a wurcs:MS
      rdfs:label "Aad211d2h-2a_2-6_5%2ANCC%2F3%3DO"

**Comment by yamadaissaku** [comment]
<http://rdf.glycoinfo.org/glycan/wurcs/2.0/Monosaccharide/WURCS=2.0/1,1,0/[a2122h-1b_1-5]/1/>
  a wurcs:Monosaccharide ;
  sio:SIO_000300 "a2122h-1b_1-5" . # http://semanticscience.org/resource/SIO_000300.rdf

sioを使うとこのようなトリプルかな。
今のWURCS−RDFには、  sio:SIO_000300 "a2122h-1b_1-5" は入ってないです。

**Comment by aokinobu** [comment]
this is actually a wurcs-only issue.  Please ignore.
